import axios from "axios";
import { getUser, clearUser } from "../utils/storage";

const BASE_URL = import.meta.env.VITE_API_BASE_URL || "http://localhost:8080";

const axiosInstance = axios.create({
  baseURL: BASE_URL,
  headers: { "Content-Type": "application/json" },
  timeout: 10000,
});

let isHandling401 = false;
let logoutCallback = null;
export const registerLogoutHandler = (fn) => { logoutCallback = fn; };

// Helper function to check if the JWT token is expired
const isTokenExpired = (token) => {
  if (!token) return true;
  try {
    const payload = JSON.parse(atob(token.split('.')[1]));
    // payload.exp is in seconds, Date.now() is in milliseconds
    return payload.exp * 1000 < Date.now();
  } catch (e) {
    return false; // If decoding fails, let the request pass and let the server handle the 401
  }
};

axiosInstance.interceptors.request.use((config) => {
  const user = getUser();
  
  if (user?.token) {
    // Check expiry before each request
    if (isTokenExpired(user.token)) {
      clearUser(); // Using the clearUser function imported at the top
      
      if (logoutCallback) {
        logoutCallback();
      } else {
        window.location.href = '/login?reason=expired';
      }
      return Promise.reject(new Error('Session expired'));
    }
    
    config.headers["Authorization"] = `Bearer ${user.token}`;
  }

  // FIX: When body is FormData (e.g. /park image upload), the instance-level
  // "Content-Type: application/json" must be fully deleted so the browser can
  // set "multipart/form-data; boundary=..." automatically.
  // The boundary is generated by the browser and REQUIRED for Spring to parse
  // the multipart parts. Without this fix, every image upload returns 400.
  //
  // In axios 1.x headers are stored as an AxiosHeaders instance — plain JS
  // `delete config.headers["Content-Type"]` removes the property wrapper but
  // leaves the internal map intact. The correct call is the AxiosHeaders method.
  if (config.data instanceof FormData) {
    if (typeof config.headers.delete === "function") {
      config.headers.delete("Content-Type"); // axios 1.x
    } else {
      delete config.headers["Content-Type"]; // axios 0.x fallback
      if (config.headers.common) delete config.headers.common["Content-Type"];
      if (config.headers.post)   delete config.headers.post["Content-Type"];
    }
  }

  return config;
});

axiosInstance.interceptors.response.use(
  (res) => res,
  (error) => {
    const status = error.response?.status;

    // Only treat 401 as a logout trigger for real auth failures.
    // Domain-level 401s (e.g. wrong OTP) include a specific message and must
    // NOT log the user out — they should be handled by the calling component.
    const responseMessage = error.response?.data?.message || "";
    const isOtpError = responseMessage.toLowerCase().includes("otp");

    if (status === 401 && !isHandling401 && !isOtpError) {
      isHandling401 = true;
      if (logoutCallback) {
        logoutCallback();
      } else {
        clearUser();
        window.location.href = "/login";
      }
      setTimeout(() => { isHandling401 = false; }, 2000);
    }

    if (status === 403) {
      console.error("403 Forbidden on:", error.config?.url);
      window.dispatchEvent(new CustomEvent("sp:forbidden", { detail: { url: error.config?.url } }));
    }

    return Promise.reject(error);
  }
);

export default axiosInstance;